Improved deployment of secrets strategy

diff --git a/nixsys-setup b/nixsys-setup
--- a/nixsys-setup
+++ b/nixsys-setup
@@ -16,6 +16,14 @@ readonly RED="$(tput setaf 1)"
 SCRIPTNAME=$(readlink -f "$0")
 SCRIPTDIR=$(dirname "$SCRIPTNAME")
 
+function cleanup() {
+    rm -rf ~/.deploy
+    printf "${ESC}"
+}
+
+trap cleanup EXIT INT TERM QUIT
+
+
 # Script to clone the mymacnix repo, stow the HOME subfolder in the repo and
 # install and configure nix-darwin
 
@@ -47,6 +55,95 @@ function get_gitfolder () {
         printf "$prompt"
     done
     eval "export gitfolder=$HOME/$folder"
+}
+
+# Function to check if Remote Login is active
+function is_sshd_on() {
+    sudo systemsetup -getremotelogin | grep -q "On"
+    return $?
+}
+
+# Function to deploy secrets
+function deploy_secrets() {
+    mkdir ~/.deploy
+    chmod 700 ~/.deploy
+
+    ## 1. Will try automated but legacy command to enable Remote Login
+    #    - but it may not work - so will fall back to manual if it fails
+    print_arrow "Attempting automated legacy command to enable Remote Login"
+    sudo -H /bin/launchctl load -w /System/Library/LaunchDaemons/ssh.plist
+    sleep 2
+    if ! is_sshd_on; then
+        ## 1a. Failed automated enabling of Remote Login - fallback to manual
+        print_arrow "Failed to auto-enable Remote Login via legacy launchctl command - falling back to manual"
+        printf "${RED}Go to ${BOLD}System Settings> General> Sharing${ESC}\n"
+        printf "${RED}Toggle ${BOLD}Remote Login${ESC}${RED} to ${BOLD}On.${ESC}\n\n"
+        print_arrow "Waiting for you to enable Remote Login"
+        printf "${GREEN}Will automatically continue after Remote Login is enabled${ESC}"
+
+        # Wait the Remote Login status to be enabled
+        while ! is_sshd_on; do
+            printf "${GREEN}.${ESC}"
+            sleep 2
+        done
+    fi
+
+    print_arrow "Remote Login is ENABLED\n"
+
+    USER_NAME=$(/usr/bin/id -un)
+    IP_ADDR=$(/usr/bin/osascript -e "IPv4 address of (system info)")
+
+    ## Need to wait for deploy.map and token to appear first
+    printf "${GREEN}Waiting for deploy.map and token in ~/.deploy folder...${ESC}\n"
+    if [ ! -f ~/.deploy/deploy.map ] || [ ! -f ~/.deploy/token ]; then
+        printf "${RED}At the remote host, do the following:${ESC}\n"
+        printf "${RED}${BOLD}1. Make a copy of the installScript/deploy-sample.map and edit it to select the appropriate secrets to deploy from 1Password${ESC}\n"
+        printf "${RED}${BOLD}2. Execute the installScripts/scpdeploy.sh script and enter ${USER_NAME}@${IP_ADDR} as the Remote Host, select the 1Password Vaults that need to be read and the deploy.map file to copy${ESC}\n"
+
+        while [ ! -f ~/.deploy/deploy.map ] || [ ! -f ~/.deploy/token ]; do
+          printf "${GREEN}.${ESC}"
+          sleep 2
+        done
+        printf "\n"
+    fi
+
+    ## Initialize OP_SERVICE_ACCOUNT_TOKEN
+    OP_SERVICE_ACCOUNT_TOKEN="$(cat ~/.deploy/token)" 
+    export OP_SERVICE_ACCOUNT_TOKEN
+
+    grep -vE '^\s*(#|$)' ~/.deploy/deploy.map | while IFS="|" read -r target secret mode; do
+
+      # Trim leading/trailing whitespace WITHOUT using xargs
+      # This syntax is pure bash and safe for spaces inside the path
+      target="${target#"${target%%[![:space:]]*}"}"
+      target="${target%"${target##*[![:space:]]}"}"
+
+      secret="${secret#"${secret%%[![:space:]]*}"}"
+      secret="${secret%"${secret##*[![:space:]]}"}"
+
+      mode="${mode#"${mode%%[![:space:]]*}"}"
+      mode="${mode%"${mode##*[![:space:]]}"}"
+      #
+      # 2. MANUALLY EXPAND TILDE (~)
+      # If target starts with ~/, replace it with the $HOME path
+      if [[ "$target" == "~/"* ]]; then
+        target="${HOME}${target#\~}"
+      fi
+
+      echo "Deploying to: '$target' with mode $mode"
+
+      # Ensure parent directory exists
+      mkdir -p "$(dirname "$target")"
+
+      # Use quotes around variables to handle spaces in the CLI call
+      op read "$secret" --out-file "$target" --force --file-mode $mode
+
+    done
+
+    # Clear the OP_SERVICE_ACCOUNT_TOKEN
+    unset OP_SERVICE_ACCOUNT_TOKEN
+    # Remove the ~/.deploy directory
+    rm -rf ~/.deploy
 }
 
 ## Test to confirm nix has been installed
@@ -167,11 +264,20 @@ if [ $? -ne 0 ]; then
     export BRANCH
     export REPOHOST
     export GREEN
+    export RED
+    export BOLD
     export ESC
+    export FN_print_arrow=$(whence -f print_arrow)
+    export FN_is_sshd_on=$(whence -f is_sshd_on)
+    export FN_deploy_secrets=$(whence -f deploy_secrets)
     [ -f /etc/zshenv ] && . /etc/zshenv
     [ -f /etc/zprofile ] && . /etc/zprofile
     [ -f /etc/zshrc ] && . /etc/zshrc
-    nix-shell -p git stow openssh age --command '
+    NIXPKGS_ALLOW_UNFREE=1 nix-shell -p git stow openssh age _1password-cli --command '
+    eval "$FN_print_arrow"
+    eval "$FN_is_sshd_on"
+    eval "$FN_deploy_secrets"
+
     echo "Populating ~/.ssh/known_hosts with public keys of github.com and gitlab.com"
     # Save current umask to set temporary umask
     save_umask=$(umask)
@@ -181,6 +287,9 @@ if [ $? -ne 0 ]; then
     mkdir -p ~/.ssh
     ssh-keyscan github.com >> ~/.ssh/known_hosts
     ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
+
+    # Deploy secrets
+    deploy_secrets
 
     # Generate age public keys if missing
     if [ -f ~/.age/key.txt ] && [ ! -f ~/.age/public.txt ]; then
